name: personalizeguidanceforahealthyheart
description: Personalize guidance for a healthy heart.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_messaging: ^9.1.3
  firebase_storage: ^8.0.0
  firebase_core: ^1.0.0
  firebase_database: ^6.1.0
  fluttertoast: ^7.1.8
  email_validator: ^1.0.6
  cached_network_image:
  permission_handler: ^6.1.0
  google_fonts: ^2.0.0
  fl_chart: ^0.36.0
  convex_bottom_bar: ^3.0.0
  day_night_time_picker: ^1.0.2
  firebase_auth: ^1.0.0
  google_sign_in: ^5.0.0
  flutter_slidable: ^0.5.7
  rflutter_alert: ^2.0.2
  ml_algo: ^16.0.2
  ml_dataframe: ^0.5.1
  ml_preprocessing: ^6.0.0
  flutter_svg: ^0.22.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/meal_sample.png
    - assets/img/user_sample.png
    - assets/img/logo.png
    - assets/img/login_bg.png
    - assets/img/logo.svg
    - assets/img/logowhite.svg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

